[40기 윤형준] ADD: DB Migration file 생성
wecode-bootcamp-korea/40-2nd-BE1Run-backend pull request #2
Opened 2022-12-27 14:40 UTC by hysy9255

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [x] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- DB Migration file 생성

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- ERD에 기반하여 Migration file 작성

2022-12-28 02:53 UTC, kyeongraekim requested changes

2022-12-28 02:53 UTC, kyeongraekim commented on db/migrations/20221225142824_movies.sql
> +    opening_date VARCHAR(500) NOT NULL,
opening_date는 별도로 기록하고 계신 영화의 상영날짜에서 최소 날짜를 구하면 되지 않을까요? 영화 날짜에 대한 기획이 변경될 때마다 opening date에 있는 날짜를 수동으로 작성해야된다는게 번거로울 수 있을 것 같네요!~

2022-12-28 02:53 UTC, kyeongraekim commented on db/migrations/20221227092349_users.sql
> +    social_id VARCHAR(100) NOT NULL,
카카오로부터 전달 받은 id값이 담길텐데 카카오는 long type으로 해당 내용을 보낼 것 입니다. API 공식문서에서 해당 내용을 찾아서 인지해주신 후, long type에 가장 상응하는 mysql에서의 데이터타입으로 변경해주세요!~

또한 해당 id가 kakao_id 인지 google_id인지 모를 수 있으니 상호명을 명시하는 것도 좋을 것 같네요!~

2022-12-28 02:53 UTC, kyeongraekim commented on db/migrations/20221227092745_reservation.sql
> +    CONSTRAINT reservations_status_id_fkey FOREIGN KEY(status_id) REFERENCES reservation_status(id)
중복 예약을 막으려면 screen_id, user_id 외래키 물려있는 내용이 unique 제약 조건이 들어있어야 하겠네요! 예전 위스타그램 과제의 좋아요에 복수의 컬럼을 향한 제약조건을 어떻게 걸었는지 곰곰히 떠올려주세요!~

2022-12-29 01:20 UTC, hysy9255 commented on db/migrations/20221227092745_reservation.sql
> +    CONSTRAINT reservations_status_id_fkey FOREIGN KEY(status_id) REFERENCES reservation_status(id)
저희가 기존에 reservation 테이블의 대한 기획 다음과 같이 하였습니다.  

한명의 유저가 한개 이상의 좌석을 예약하면 해당 테이블에 하나의 user_id가 여러개의 screen_id와 조합이되어 여러개의 행으로써 들어갈 수 있도록 기획하여서 일부러 unique constraint를 넣지 않았습니다.

이 부분에 대해서 한번 검토 부탁 드립니다.

2022-12-29 02:04 UTC, hysy9255 commented on db/migrations/20221227092745_reservation.sql
> +    CONSTRAINT reservations_status_id_fkey FOREIGN KEY(status_id) REFERENCES reservation_status(id)
> 저희가 기존에 reservation 테이블의 대한 기획 다음과 같이 하였습니다.
> 
> 한명의 유저가 한개 이상의 좌석을 예약하면 해당 테이블에 하나의 user_id가 여러개의 screen_id와 조합이되어 여러개의 행으로써 들어갈 수 있도록 기획하여서 일부러 unique constraint를 넣지 않았습니다.
> 
> 이 부분에 대해서 한번 검토 부탁 드립니다.

저희가 기존에 reservation 테이블의 대한 기획 다음과 같이 하였습니다.

한명의 유저가 한개 이상의 좌석을 예약하면 해당 테이블에 하나의 user_id가 여러개의 screen_id와 조합이되어 여러개의 행으로써 들어갈 수 있도록 기획하여서 일부러 unique constraint를 넣지 않았습니다.

이 부분에 대해서 한번 검토 부탁 드립니다.

2022-12-29 02:05 UTC, hysy9255 commented on db/migrations/20221227092745_reservation.sql
> +    CONSTRAINT reservations_status_id_fkey FOREIGN KEY(status_id) REFERENCES reservation_status(id)
> 중복 예약을 막으려면 screen_id, user_id 외래키 물려있는 내용이 unique 제약 조건이 들어있어야 하겠네요! 예전 위스타그램 과제의 좋아요에 복수의 컬럼을 향한 제약조건을 어떻게 걸었는지 곰곰히 떠올려주세요!~

저희가 기존에 reservation 테이블의 대한 기획 다음과 같이 하였습니다.

한명의 유저가 한개 이상의 좌석을 예약하면 해당 테이블에 하나의 user_id가 여러개의 screen_id와 조합이되어 여러개의 행으로써 들어갈 수 있도록 기획하여서 일부러 unique constraint를 넣지 않았습니다.

이 부분에 대해서 한번 검토 부탁 드립니다.

2022-12-29 09:08 UTC, hysy9255 commented on db/migrations/20221225142824_movies.sql
> +    opening_date VARCHAR(500) NOT NULL,
저희 이번 프로젝트는 BMT라는 영화관의 사업이 이미 지속되던 와중에 웹사이트만 새로 런칭하는 것으로 기획을 하였습니다. 

해당 웹사이트의 런칭 시점과 영화를 웹사이트를 통해 예매가 가능한 시점이 동일 합니다. 하지만 영화관 사업 및 영화 상영은 웹사이트 런칭 전에도 시행되고 있는 설정입니다. 따라서 opening date는 영화마다 다른 것으로 설정되어 있고, 저희가 DB에 데이터로써 가지고 있는 가장 이른 날짜는 웹사이트를 런칭하는 시점이기에 가장 이른 날짜로 opening_date를 관리한다면 저희의 기획과 상이한 결과가 있을 것 같습니다. 

이 부분에 대해서 한번 검토 부탁 드립니다.

2022-12-29 09:08 UTC, hysy9255 commented on db/migrations/20221225142824_movies.sql
> +    opening_date VARCHAR(500) NOT NULL,
> opening_date는 별도로 기록하고 계신 영화의 상영날짜에서 최소 날짜를 구하면 되지 않을까요? 영화 날짜에 대한 기획이 변경될 때마다 opening date에 있는 날짜를 수동으로 작성해야된다는게 번거로울 수 있을 것 같네요!~

저희 이번 프로젝트는 BMT라는 영화관의 사업이 이미 지속되던 와중에 웹사이트만 새로 런칭하는 것으로 기획을 하였습니다.

해당 웹사이트의 런칭 시점과 영화를 웹사이트를 통해 예매가 가능한 시점이 동일 합니다. 하지만 영화관 사업 및 영화 상영은 웹사이트 런칭 전에도 시행되고 있는 설정입니다. 따라서 opening date는 영화마다 다른 것으로 설정되어 있고, 저희가 DB에 데이터로써 가지고 있는 가장 이른 날짜는 웹사이트를 런칭하는 시점이기에 가장 이른 날짜로 opening_date를 관리한다면 저희의 기획과 상이한 결과가 있을 것 같습니다.

이 부분에 대해서 한번 검토 부탁 드립니다.

2022-12-30 09:02 UTC, kyeongraekim approved these changes

2022-12-30 09:02 UTC, merged