[40기 김영석] 영화검색 기능 구현
wecode-bootcamp-korea/40-2nd-BE1Run-backend pull request #5
Opened 2023-01-02 02:46 UTC by yyeongseok

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
영화 제목 검색 기능 추가

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
검색창에 키워드를 입력했을때, 키워드가 들어간 영화 제목을 검색합니다.

<br />

## :: 테스트 결과 이미지
포스트맨 통신 결과 이미지
<img width="1013" alt="스크린샷 2023-01-02 오전 11 38 43" src="https://user-images.githubusercontent.com/117704920/210191886-9bf44875-3cf8-4c3f-9933-4ff4e59025b5.png">
유닛 테스트 결과 이미지
<img width="558" alt="스크린샷 2023-01-02 오전 11 44 17" src="https://user-images.githubusercontent.com/117704920/210191894-c15026d0-5018-4388-a517-8d6de87b2782.png">
<br />

## :: 기타 질문 및 특이 사항

2023-01-02 08:44 UTC, kyeongraekim requested changes

2023-01-02 08:44 UTC, kyeongraekim commented on tests/movie.test.js
> +        await dataSource.destroy();
현재 코드 상에서는 해당 내역이 필요 없어 보이네요! 해당 세 줄의 의미가 무엇인지 혹시 파악이 되셨을까요?

2023-01-02 08:44 UTC, kyeongraekim commented on api/models/movieDao.js
> +        err
catch 이후에 해당 err는 어떠한 사후 동작의 의미가 담겨있는 걸까요?

2023-01-03 01:48 UTC, yyeongseok commented on tests/movie.test.js
> +        await dataSource.destroy();
네, 위의 두줄은 외래키 관리하는 코드여서 필요없는것 같습니다. 마지막에 코드정리하면 놓친것 같습니다.
18번째 줄은 해당 테스트가 끝나고 나면 데이스베이스와 연결을 종료하는 코드입니다.

2023-01-03 01:52 UTC, yyeongseok commented on api/models/movieDao.js
> +        err
해당 부분을 통해서 query에서 발생할수 있는 빌트인 에러를 확인하고자 하였습니다.

2023-01-03 02:07 UTC, kyeongraekim requested changes

2023-01-03 02:07 UTC, kyeongraekim commented on tests/movie.test.js
> +        await dataSource.destroy();
넵 영석님 잘 파악해주셨네요! 그렇다면 관련하여 수정해주시면 감사하겠습니다!
해당 내용을 유지하는 기획이시라면, 외래키를 잠시 껐다가 키는 행위는 보통 유닛테스트 시 임의의 목데이터를 빈 데이터베이스에 쉽게 삽입(Insert)하고 쉽게 삭제(Truncate)하기 위한 목적이 있습니다.  
해당 내용을 삭제하는 기획이시라면, 테스트 데이터베이스에서 직접 mock 데이터를 관리하는 모습이 있어야 할 것 같네요!

2023-01-03 02:07 UTC, kyeongraekim commented on api/models/movieDao.js
> +        err
네 그러면 해당 err를 catch 해주셨으니 내부 캐치 함수에서의 이후 동작들도 thorw, return 등의 행위를 선언해주면 좋을 것 같아 보입니다!~ 
만일 단순 확인용이고, global error handler 등을 이용할 계획이시라면, 최종 푸시 코드에서는 try-catch 구조를 없애는 기획으로 가도 좋을것 같아 보이네요!~

2023-01-03 04:47 UTC, kyeongraekim requested changes

2023-01-03 04:47 UTC, kyeongraekim commented on tests/movie.test.js
> +        .expect
이곳 expect문은 미완성의 상태처럼 보이는데 한 번 확인 부탁드려요!~

2023-01-04 01:44 UTC, kyeongraekim requested changes

2023-01-04 01:44 UTC, kyeongraekim commented on tests/movie.test.js
> +                "director",15000,"actors","trailer_videos_url","still_cut_image"
이 부분도 가독성 좋게 라인 브레이킹이 들어가면 좋을 것 같습니다.

2023-01-04 01:44 UTC, kyeongraekim commented on tests/movie.test.js
> +        .expect(200)
get에 대한 최종 결과값이 커리문으로 확인이 되어야겠지요? 상태코드 뿐만 아니라 위에 Mock Data로 넣어준 결과값을 확인할 수 있게 수정해주세요!~

2023-01-04 02:30 UTC, merged